import type { Metadata } from "next";
import "./globals.css";
import Cabecalho from "@/components/Cabecalho/Cabecalho";
import Footer from "@/components/Rodape/Footer";
import { AuthProvider } from "@/context/AuthContext";

export const metadata: Metadata = {
  title: "Portal-PCD",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-br">
      <body>
        <AuthProvider>
        <Cabecalho/>
        {children}
        <Footer contatos={["exemploemail@.com","0000-87572"]} parcerias={["FIAP","CCR"]}/>
        </AuthProvider>
        </body>
    </html>
  );
}
